CREATE TYPE AMENITY AS ENUM ('WiFi', 'AC', 'Heating', 'TV', 'Fridge', 'Closet', 'Balcony', 'Desk', 'Couch', 'Microwave', 'Safe', 'Pool', 'Gym', 'Parking');
CREATE TYPE VIEW AS ENUM ('Ocean', 'Mountain', 'City');
CREATE TYPE EMPLOYEE_ROLE AS ENUM ('regular', 'admin');

CREATE DOMAIN RATING AS INTEGER CHECK (VALUE >= 1 AND VALUE <= 5);
CREATE DOMAIN PRICE AS DECIMAL(10, 2) CHECK (VALUE >= 0);
CREATE DOMAIN CAPACITY AS INTEGER CHECK (VALUE = 1 OR VALUE = 2 OR VALUE = 3 OR VALUE = 4);
CREATE DOMAIN PHONE_NUMBER AS CHAR(10) CHECK (VALUE ~ '^[0-9]{10}$');
CREATE DOMAIN EMAIL AS VARCHAR(255) CHECK (VALUE ~ '^[a-zA-Z0-9]([a-zA-Z0-9]|\-|\.)*[a-zA-Z0-9]@(([a-zA-Z]+\.)+[a-zA-Z]{2,3})$');
CREATE DOMAIN POSITIVE_INTEGER AS INTEGER CHECK (VALUE > 0);
